name: Android CI (Whisper Phone ASR)

on:
  pull_request:
    branches: [ "feature/whisper-phone-asr" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install \
            "cmdline-tools;latest" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;27.0.12077973" \
            "cmake;3.22.1"

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Build (externalNativeBuild + assemble OfflineDebug)
        run: |
          ./gradlew --stacktrace \
            -Pandroid.compileSdk=34 \
            -Pandroid.targetSdk=34 \
            -Pandroid.buildToolsVersion=34.0.0 \
            :app:externalNativeBuildOfflineDebug \
            :app:assembleOfflineDebug

    # Note: CI can stay on Android 34 platform even if local uses 36.
    # Modules read compileSdk/targetSdk from gradle.properties; we override
    # via -P flags above if the runner lacks API 36.


