name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            cmdline-tools;latest
            platforms;android-35
            build-tools;35.0.0

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew :app:assembleOfflineDebug :wear:assembleOfflineDebug :app:testOfflineDebug --stacktrace

      - name: Upload app APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-offline-debug-apks
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: error

      - name: Upload wear APKs
        uses: actions/upload-artifact@v4
        with:
          name: wear-offline-debug-apks
          path: wear/build/outputs/apk/**/*.apk
          if-no-files-found: warn
