name: Android CI (stable)

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21 (Temurin) + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # Use Android 34 (stable) + NDK/CMake for native build
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install \
            "cmdline-tools;latest" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;29.0.14033849" \
            "cmake;3.22.1"

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Show installed SDK packages (first 200 lines)
        run: |
          sdkmanager --list | sed -n '1,200p' || true
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-$ANDROID_HOME}"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build (offline flavor) + unit tests (override to API 34 on CI)
        run: |
          ./gradlew --version
          ./gradlew clean \
            -Pandroid.compileSdk=34 \
            -Pandroid.targetSdk=34 \
            -Pandroid.buildToolsVersion=34.0.0 \
            :app:externalNativeBuildOfflineDebug \
            :app:assembleOfflineDebug \
            :wear:assembleOfflineDebug \
            :app:testOfflineDebug \
            --stacktrace --no-daemon --warning-mode all

      - name: Upload app APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-offline-debug-apks
          path: app/build/outputs/**/*.apk
          if-no-files-found: error

      - name: Upload wear APKs
        uses: actions/upload-artifact@v4
        with:
          name: wear-offline-debug-apks
          path: wear/build/outputs/**/*.apk
          if-no-files-found: warn
