name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-java-and-gradle:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Gradle and Java versions
        shell: pwsh
        run: .\\gradlew.bat --version

      # Note: Full Android builds require Android SDK/NDK setup on CI.
      # This workflow intentionally focuses on ensuring JDK 21 is used for Gradle runtime.

